name = "8Bit Client 1.19.2"
author = "RM20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddb1056045d9d36c1c038382da0b77ec5d2f0bb37a96cf38131837c2e0a6ad8e"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
