name = "8Bit Client 1.19.2"
author = "RM20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddadb8ec591b7497bb1db8797d82d59b4a4a5f6a1e0a08f77eae4a015258b237"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
