name = "8Bit Client 1.19.2"
author = "RM20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb97988bc4ce15b0e8db7211fe3b6e1421e52860af9566838b5c8b79b27ef35c"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
