name = "8Bit Client 1.19.2"
author = "RM20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2106cba5e25142ae7a74aa850af89dd6972841ad85de43093464f923e2e5b3e"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
