
#To sit it properly, visit the mod wiki website for more information:
#https://github.com/ixDarkLorD/ModpackManager/wiki
[Manifest]
	#Modpack Identifier
	identifier = "8Bit client"
	project_id_or_url = "https://raw.githubusercontent.com/rm20killer/8bit-unofficial-modpack/main/1.19.2%20Basic/Manifest.json"
	#Modpack Title | Syntax: ${version}, ${mcversion}, ${gamestate}
	title = "8Bit client ${version} - ${gamestate}"
	#Modpack Version
	version = "v0.0.3"

[Visuals]
	#Range: 0.0 ~ 1.0
	durability_display_size = 0.5
	#Durability Display Visibility and Size
	durability_display_visibility = false

[General]
	#Startup Title Visibility and Text
	startup_title_visibility = true
	startup_title_text = "Please wait! Starting up..."
	#Gamestate Visibility Mode | Syntax: ALL, PLAYING_MODE_AND_EXTRA, PLAYING_MODE_AND_PAUSE_SCREEN, ONLY_PLAYING_MODE
	gamestate_visibility = "ALL"
	#Startup Loading Visibility and Text
	loading_screen_gamestate_visibility = true
	#CFU Button(Checking for Updates) Behavior
	is_first_time_pressed = true
	loading_screen_text = "Loading the game..."

