name = "8Bit Client 1.20.4"
author = "RM20"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0655fadfeb15a1e5e74fa191fe4570af649adb124274be148a790229265be540"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
