name = "8Bit Client 1.20.4"
author = "RM20"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "253f41b5ac9cd3c6abae605735a887774202762dbe8a2aac82093fe17ff81eea"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
