name = "8Bit Client 1.21.1"
author = "RM20"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df17bf700992e425d2e554d12f5f0e33dbc207e15841e0de56c86dbfafe7a82b"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
