jobs:
  on:
    release:
      types: [published]
  build:
    steps:
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          # You don't need this section if you don't want to publish
          # your assets to Modrinth
          modrinth-id: uJzGt9Fo
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
